load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "MHPrinterLib",
    srcs = ["MHPrinter.cc"],
    hdrs = ["MHPrinter.h"],
    deps = [],
)

cc_binary(
    name = "MHPrinterMain",
    srcs = ["MHPrinterMain.cc"],
    deps = [],
)

